### ISSUE TITLE
First page is blank

### ISSUE THREAD

**Issue by ghost** [ryanwiemer/gatsby-starter-gcn#100]
I changed basePath to articles and when loading the website, the first page is blank
how can I create a custom home page that shows an image?

**Comment by ryanwiemer** [comment]
@drwhoooois Create a file named `index.js` under [`/src/pages/`](https://github.com/ryanwiemer/gatsby-starter-gcn/tree/master/src/pages) and that will be your homepage. Place whatever content, etc. you want.

**Comment by ghost** [comment]
thank you
