### ISSUE TITLE
Draft content on Contentful showing

### ISSUE THREAD

**Issue by sparker888** [ryanwiemer/gatsby-starter-gcn#19]
I see that draft content on Contentful (posts) is showing up for local gatsby develop. Is this intended?

**Comment by ryanwiemer** [comment]
@sparker888 yes, that is intended. Draft content only shows up in develop mode not in production. 

If you wanna see what production looks like locally you can use `gatsby build` and the `gatsby serve` commands.

**Comment by sparker888** [comment]
OK, thanks!
