### ISSUE TITLE
Contentful to GitLab

### ISSUE THREAD

**Issue by githubr** [ryanwiemer/gatsby-starter-gcn#21]
Thank you for writing this and let us use it.

I have followed the instruction and been able to get my site up and running, including the automatic Netlify deployment when I publish something on Contentful.

I am wondering if there is a way to also push content from Contentful to GitLab? I like the idea that I have a copy of my content stored in GitLab. Thank you.

**Edit**

After playing with it a little bit more, I found that doing ```gatsby build``` actually pull Contentful content and then I can push it to GitLab. Is it possible to do this automatically using Netlify deployment?

**Comment by ryanwiemer** [comment]
Basically what you are describing is an automated backup of the site triggered by an event.  

Maybe look at [Netlify Functions](https://www.netlify.com/docs/functions/) to see how you could setup a script trigged every time that you build the site.

**Comment by ryanwiemer** [comment]
Closing this issue as it is more of general question not specifically related to the repo. 

If you figure out a method that works for you feel free to share what you learned. 

Thanks.

**Comment by githubbr** [comment]
Thanks for the pointer. Yes the aim is to have a backup of the static contents. I'll check out Netlify Function
