### ISSUE TITLE
gatsby-netlify-plugin causes an error

### ISSUE THREAD

**Issue by daydream05** [ryanwiemer/gatsby-starter-gcn#22]
This happens when trying to deploy to netlify. I've followed every instructions.
```
error Plugin gatsby-plugin-netlify returned an error
4:35:17 PM: 
4:35:17 PM:   Error: Cannot find module '/opt/build/repo/public/stats.json'
4:35:17 PM:   
4:35:17 PM:   - v8-compile-cache.js:159 require
4:35:17 PM:     [repo]/[v8-compile-cache]/v8-compile-cache.js:159:20
4:35:17 PM:   
4:35:17 PM:   - plugin-data.js:65 makePluginData
4:35:17 PM:     [repo]/[gatsby-plugin-netlify]/plugin-data.js:65:15
4:35:17 PM:   
4:35:17 PM:   - gatsby-node.js:71 _callee$
4:35:17 PM:     [repo]/[gatsby-plugin-netlify]/gatsby-node.js:71:51
4:35:17 PM:   
4:35:17 PM:   - gatsby-node.js:101 Object.onPostBuild
4:35:17 PM:     [repo]/[gatsby-plugin-netlify]/gatsby-node.js:101:18
4:35:17 PM:   
4:35:17 PM:   - api-runner-node.js:104 runAPI
4:35:17 PM:     [repo]/[gatsby]/dist/utils/api-runner-node.js:104:37
4:35:17 PM:   
4:35:17 PM:   - api-runner-node.js:173 mapSeries
4:35:17 PM:     [repo]/[gatsby]/dist/utils/api-runner-node.js:173:25
4:35:17 PM:   
```

###Environment:

I've modified it to comply with v2  so i don't think it should matter.

System:
    OS: macOS High Sierra 10.13.3
    CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.0.0 - /usr/local/bin/node
    Yarn: 1.6.0 - ~/.yarn/bin/yarn
    npm: 6.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.87
    Firefox: 57.0.3
    Safari: 11.0.3
  npmPackages:
    gatsby: next => 2.0.0-beta.1
    gatsby-image: ^2.0.0-beta.1 => 2.0.0-beta.1
    gatsby-link: ^1.6.44 => 1.6.44
    gatsby-plugin-canonical-urls: ^1.0.18 => 1.0.18
    gatsby-plugin-feed: ^1.3.22 => 1.3.25
    gatsby-plugin-google-analytics: ^1.0.31 => 1.0.31
    gatsby-plugin-manifest: ^1.0.22 => 1.0.27
    gatsby-plugin-netlify: ^1.0.19 => 1.0.21
    gatsby-plugin-nprogress: ^1.0.14 => 1.0.14
    gatsby-plugin-offline: ^1.0.16 => 1.0.18
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11
    gatsby-plugin-sitemap: ^1.2.23 => 1.2.25
    gatsby-plugin-styled-components: ^2.0.11 => 2.0.11
    gatsby-plugin-svgr: ^1.0.1 => 1.0.1
    gatsby-plugin-typography: ^1.7.19 => 1.7.19
    gatsby-remark-prismjs: ^2.0.2 => 2.0.4
    gatsby-source-contentful: next => 2.0.1-beta.1
    gatsby-source-filesystem: ^1.5.36 => 1.5.39
    gatsby-transformer-remark: ^1.7.41 => 1.7.44
    gatsby-transformer-sharp: ^2.1.1-beta.1 => 2.1.1-beta.1
  npmGlobalPackages:
    gatsby-cli: 1.1.58

**Comment by ryanwiemer** [comment]
@daydream05, 

That appears to be a bug with `v2` and the `gatsby-netlify-plugin`. Hopefully it gets resolved soon. Just for awareness I am holding back on updating my repo to use `v2` until bugs like these are resolved.

**Comment by ryanwiemer** [comment]
I am closing this issue for now since I *believe* it is an upstream issue with Gatsby `v2` and not specifically this repo. 

If I mistaken though and you can replicate the issue on Gatsby `v1` let me know and I can investigate it further.  

Thanks!

**Comment by daydream05** [comment]
Thank you for the response! Definitely an issue with v2. Thanks for this starter btw! Love the SEO component!
