### ISSUE TITLE
Google Analytics 

### ISSUE THREAD

**Issue by githubbr** [ryanwiemer/gatsby-starter-gcn#23]
Other than putting in my Google analytics ID on Netlify's deployment variable, is there anything else I need to do? I've done that and it doesn't seem that GA is taking. Thanks

**Comment by ryanwiemer** [comment]
Did you name the deployment variable exactly `GOOGLE_ANALYTICS`? It will only work if you do that. 

The environment variable is used in the [`gatsby-config`](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/gatsby-config.js#L70) file along with the `gatsby-plugin-google-analytics`

**Comment by githubr** [comment]
Hi @ryanwiemer thanks for your response. Yes I named the variable exactly that.

~~~I don't seem to find any reference to ```gatsby-plugin-google-analytics``` in my ```gatsby-config``` file.~~~

UPDATE: found it in the config file.

**Comment by githubr** [comment]
I can confirm it is now tracking. I think it was just the delay. Thank you.

**Comment by ryanwiemer** [comment]
Okay cool. Glad it is working for you. I'm gonna close out this ticket.
