### ISSUE TITLE
Multilingual functionality

### ISSUE THREAD

**Issue by Silisav** [ryanwiemer/gatsby-starter-gcn#27]
Hey Ryan, 

Thanks for creating the repo and adding all the instructions for setting things up! 
I was wondering if you can think of a way of getting this to work with different contentful locales. I spent a couple of days trying to filter page and post queries for `node_locale` and switch languages but it's quite tricky. Any ideas or plans of implementing this in the future?

Thanks again!

**Comment by ryanwiemer** [comment]
@Silisav, 

Glad you are finding the repo useful! To be honest I don't have any experience working with different Contentful locales. So at this time it is not on the roadmap. With that said I am open to suggestions for collaboratively working towards that goal if it is worth the time. 

A first step would be to find a working example of a Gatsby website that does this successfully. Have you looked at the [Gatsby showcase](https://next.gatsbyjs.org/showcase/) or elsewhere to see if it has been done before?

Thanks,
Ryan

**Comment by Silisav** [comment]
There is this one: https://github.com/mccrodp/gatsby-starter-contentful-i18n 
I had a quick look and it's quite straightforward to change the query and get localised content back. For example: 

- If you add a second locale in contentful (add italian for example) 
- Make some _Page_ content type fields multilingual 
- Add some dummy content in the multilingual fields
- Finally change the page query to sthing like this: 
```
export const query = graphql`
  query pageQuery($slug: String!) {
    contentfulPage(slug: { eq: $slug }, node_locale: { eq: "it"}) {
      title
      node_locale
      slug
      metaDescription {
        internal {
          content
        }
      }
      body {
        childMarkdownRemark {
          html
          excerpt(pruneLength: 320)
        }
      }
    }
  }
`
```
you'll get the page with the italian content and english as fallback for any fields that you didn't translate. The same should work for the blog post template. The index page that gets the blog posts feed should also work with a filter in the query: `filter: { node_locale: { eq: "it" } }`

I guess the tricky part is creating the language switch. I tried to do add the `node_locale` in the gatsby-node querie's context and pass the language in a more dynamic way but that's not the right place to do it I think. I'll keep looking into it, if you have any ideas let me know :)

I think it's worth making it work since contentful offers 2 locales even for the free account for developers.

**Comment by ryanwiemer** [comment]
@Silisav, 

I am going to close out this ticket. I think multilingual functionality is interesting but perhaps out of scope for the default functionality of this starter. 

Thank you for sharing what you learned and best of luck to you if you haven't already solved this problem on your own.
