### ISSUE TITLE
Homepage fails to render correctly in Firefox for Mac

### ISSUE THREAD

**Issue by brandonkal** [ryanwiemer/gatsby-starter-gcn#3]
I really like this starter framework, it looks like a great combination of technologies. Unfortunately it doesn't seem to render properly in Firefox. Also the contentful attribution doesn't seem to load on the knw.io website.
Here is a screenshot of how it looks in Firefox Quantum. Not really why it is failing in this browser:
![gcn-firefox-render](https://user-images.githubusercontent.com/4714862/38698276-5cf289f6-3e49-11e8-8f0d-8509dc4f9ffb.png)

**Comment by ryanwiemer** [comment]
@popwebz,

Thank you for the feedback! It appears to be some unintentional format issues with using Flexbox. I will take a look and see what can be fixed and if a fallback is necessary specifically for FireFox. 

Out of curiosity do you know what version of FireFox you are using? Honestly I'm not much of a FireFox user and that probably shows with my lack of testing 🙈

If you are feeling really helpful PRs are always welcome if you notice any bugs or issues. 😉

**Comment by ryanwiemer** [comment]
@popwebz this is now fixed in `v1.0.3`. Thank you for reporting the issue. Let me know if you see any others.
