### ISSUE TITLE
Redundant meta tags

### ISSUE THREAD

**Issue by brandonkal** [ryanwiemer/gatsby-starter-gcn#36]
I noticed this while grepping through the diffs for the version 2 upgrade.
It is not a huge concern because React Helmet handles everything nicely. But since the SEO component handles the meta tags in the Layout component, those lines should probably be removed. I'll leave this here as a reminder for when I find the time to do this down the road.

**Comment by brandonkal** [comment]
I'm also curious what is going on in line 28 of Layout.js

**Comment by brandonkal** [comment]
console.log is also in the tag.js file

**Comment by ryanwiemer** [comment]
Thanks for pointing this out. I can clean that up on the next release.

**Comment by ryanwiemer** [comment]
Fixed in [`2.0.1`](https://github.com/ryanwiemer/gatsby-starter-gcn/releases/tag/v2.0.1)
