### ISSUE TITLE
Contentful API keys

### ISSUE THREAD

**Issue by kirso** [ryanwiemer/gatsby-starter-gcn#37]
Tried to insert environmental variables into netlify as per Contentful keys (access / space id) however during deployment is drops this error:

Accessing your Contentful space failed. Perhaps you're offline or the spaceId/accessToken is incorrect
Error running command: Build script returned non-zero exit code: 1

Wonder what can be wrong?

**Comment by ryanwiemer** [comment]
@kirso  Did you name the environment variables in Netlify exactly as `ACCESS_TOKEN` and `SPACE_ID`?

**Comment by kirso** [comment]
Apologies for opening an issue - the access token was different (not the content, but personal one)

**Comment by ryanwiemer** [comment]
Ah gotcha. No worries. Glad you figured it out.
