### ISSUE TITLE
Is there anyway to fix the black favicon?

### ISSUE THREAD

**Issue by daydream05** [ryanwiemer/gatsby-starter-gcn#38]
I tried changing the site icon and the plugin-manifest but I still get the default dark favicon

**Comment by ryanwiemer** [comment]
@daydream05 

Perhaps it is cached. Maybe do a hard refresh or clear the cache. Hard to say without looking at your code. Can you share a link to your repo?

**Comment by daydream05** [comment]
Cleared my browser cache. It works! Thanks
