### ISSUE TITLE
Suggestion - change attribution domain

### ISSUE THREAD

**Issue by brandonkal** [ryanwiemer/gatsby-starter-gcn#4]
Per the Contentful documentation, they updated the asset domain:
images.contentful.com → images.ctfassets.net
https://www.contentful.com/blog/2017/12/08/change-of-the-contentful-asset-domain/
They just made this change a week or so ago. Changing the url for the attribution link to the ctfassets domain will save a DNS lookup and redirect though the performance improvement will likely be negligable it would make things a bit cleaner.

**Comment by ryanwiemer** [comment]
@popwebz,

Thanks for pointing that out. It sounds pretty minor but certainly something that can easily be done. The code snippet that I am using for the logo attribution is from their official documentation: [https://www.contentful.com/r/knowledgebase/how-attribution-works/](https://www.contentful.com/r/knowledgebase/how-attribution-works/)

It looks like they haven't gotten around to updating it to use the new asset domain. I can reach out to Contentful.

**Comment by ryanwiemer** [comment]
This is now updated in `v1.0.4` 

Contentful has updated their official documentation too. 😃

**Comment by brandonkal** [comment]
Awesome. I am curious how you are using release tags . Is this just for you to keep track of changes or is netlify configured to build when the release is incremented rather than on every commit?

**Comment by ryanwiemer** [comment]
Nah. The release tags are just for my own sanity so that I keep track of things. I have it setup to build whenever I push to the `master` branch. But Netlify can do what you described. It's very configurable.
