### ISSUE TITLE
Contact form failure

### ISSUE THREAD

**Issue by johnmeredith** [ryanwiemer/gatsby-starter-gcn#40]
Hi there,
Second time I've hit this problem with the Netlify forms so hopefully it's a quick fix. 

I previously had an HTML contact for that was fialing and the original dev kindly added a honeypot. Low and behold the form submissions began to work. I notice you also have a honeypot witihn the contact component but I canot seem to get it working. 

My [repo is here](https://github.com/johnmeredith/archetextures-gatsby). 
My site on [Netlify is here](https://archetextures.netlify.com/).

Thank you!

**Comment by ryanwiemer** [comment]
Are you experiencing any issues specifically related to this repo? Or just curious in general about how to improve your Netlify contact form to reduce spam? The form provided here is a bare bones example. 

The best way to get rid of spam completely is to incorporate a recaptcha. It requires additional steps but is worth the time. 

[Example Code](https://github.com/imorente/gatsby-netlify-form-example/blob/master/src/pages/recaptcha.js)

[Netlify Blog Post](https://www.netlify.com/blog/2018/05/23/bring-your-own-recaptcha-to-netlify-forms/)

**Comment by johnmeredith** [comment]
Yes - the form submission appears to work - I get the confirmation message. But no mail forms get processed by Netlify. This was the exact same issue I received with my other Gatsby/Netfliy site. As said, the honeypot fixed it but in your case you have already thought of that.

**Comment by ryanwiemer** [comment]
Ahhh I see. I just confirmed it is not working on the prod site. This is a bug. I will investigate and report back.

**Comment by ryanwiemer** [comment]
This appears to be related to https://github.com/gatsbyjs/gatsby/issues/7997. I will release a hot fix with the work around right now. 

Thanks for catching this.

**Comment by ryanwiemer** [comment]
Fixed in [2.0.2](https://github.com/ryanwiemer/gatsby-starter-gcn/releases/tag/2.0.2)
