### ISSUE TITLE
Embedded Content - Twitter

### ISSUE THREAD

**Issue by johnmeredith** [ryanwiemer/gatsby-starter-gcn#43]
Embedded content that appears to render correctly in Contentful (e.g. tweets) do not appear on the built page. 

See [this post at the bottom](https://archetextures.netlify.com/interoperability-is-poorly-defined-and-subsequently-misused/), in the Why This Matters section.

For reference, this is how it appears in Contentful:
![embed](https://user-images.githubusercontent.com/17782555/47119725-e62b6900-d263-11e8-9b44-e615a5bc0ea8.jpg)

**Comment by ryanwiemer** [comment]
Embedded content is possible in markdown but requires additional Gatsby plugins or custom code. I have not added these in by default but I would recommend looking at the Gatsby Plugin Page if you need additional features. 

For example for this use case: https://www.gatsbyjs.org/packages/gatsby-plugin-twitter/

**Comment by johnmeredith** [comment]
Fantastic. That plugin worked great. Needs some styling to make it look better but the tweets show up.
