### ISSUE TITLE
Explore Comment Options

### ISSUE THREAD

**Issue by brandonkal** [ryanwiemer/gatsby-starter-gcn#48]
I am interested in exploring comment options. Perhaps not adding it entirely depending on your thoughts, because then it becomes more than "Gatsby Contentful and Netlify." One option that would likely be useful to people would be building a comment component that matches the theme styles and adding a note to the readme on how to include it on the pages.

After sifting through the various commenting options, I've narrowed it down to two good options:

1. Commento

This one seems to be a good route for users interested in self-hosting their comment system. There is an open-source docker container available, but there is not really any documentation on the setup process for a self-hosted route. They do have a hosted option available with some documentation available, but their terms are too open for my tastes: https://commento.io/terms

> You also give other Commento.io users permission to share your Content on other Commento.io websites and add their own Content to it (aka to reblog your Content) ... Commento has the right to reclaim your username or website’s URL due to prolonged inactivity

Not horrible, but the lack of this requirement and depth of documentation is probably reason enough to go with the small cost of Just Comments.

It is possible that the website URL thing could be an unintended side-effect of lifting it from the WP.com TOS but I wouldn't want a comment system claiming legal ownership of one of my domains!

2. Just Comments

This one looks really nice and easy to implement. It is well-documented and has some nice features such as JWT to integrate with any authentication system. https://just-comments.com/

The front-end is open sourced, and the backend API is available as a hosted option which comes out to around $0.30/20K comment page views. The styling is barebones but a sane starting point, which is nice because it makes it easy to integrate with a website's theme.

~~Kyle Matthews~~ Oleksii Rudenko wrote a nice piece on how to add it to a Gatsby blog: https://60devs.com/add-comments-to-your-gatsbyjs-blog-within-two-minutes.html

Anyway, I'd be interested to know you throughts and if something like this makes sense for this project.

**Comment by ryanwiemer** [comment]
@brandonkal, 

I was actually just looking into comment options for another project so this is good timing. Here are my thoughts on what would be needed for it to make sense for this project: 

### Requirements
* Offers some form of a free tier
* Hosted or provided by a third party service. I don't want to help people debug their docker container or some other solution like that. 😉
* Simple configuration to get up a running. For example all they need to do is provide an API key to our Comments component as a prop.
* Most importantly the website should still work even if the comments are disabled or inadvertently broken.

So with those requirements and looking at other starters that really pushes me towards either Disqus or Facebook Comments. They are both pretty bloated and large so it would be best to lazy load the comments. 

### Example
Here is the component that I made and I was testing out. Comments are loaded on click and there is a visual indicator while it loads. 

![lazy-load-comments](https://user-images.githubusercontent.com/5171579/49106470-20f7c800-f238-11e8-8d10-7f2b12c7b336.gif)

At the end of the day for me to include it in the starter it would have to be like Google Analytics which is used here. If you want to use it then cool, its set up and just add in your key as an environment variable. If not than no big deal everything still works as expected. 

Anyways, sorry for the long rant. Let me know if that makes sense or if you have other thoughts on comments.

**Comment by johnmeredith** [comment]
Isn't Disqus an option? I'm trying to add it to my clone now.

**Comment by ryanwiemer** [comment]
@johnmeredith, 

Yeah Disqus works fine and it's easy enough to add. Regardless of which 3rd party hosted comment solution you choose you probably want to lazy load it in some way. Disqus and Facebook are both very heavy and you don't want to add 500kb - 2mb or whatever it takes to load unless you are sure the user wants to see it. 

Just my two cents.

**Comment by brandonkal** [comment]
@johnmeredith Yes, Disqus is an option and easy to add. I am not a fan of the UX as it doesn't encourage comments (opinion). I am currently exploring alternatives so stay tuned. Like Ryan says, it is quite heavy (700KB) and I don't want comments to be the slowest part of my site.

If the audience is all developers (e.g. a tech blog) https://utteranc.es/ is a really slick option I found as it is all based on GitHub comments and it is fast enough to not lazy load.

**Comment by ryanwiemer** [comment]
@brandonkal haha. It looks like we had the exact same thought. 😂

**Comment by johnmeredith** [comment]
Any update chaps? ;-)

**Comment by brandonkal** [comment]
@johnmeredith I have a working simple comment system (Gatsby Comments). I am currently in the middle of a big project, but once that is done, I plan to spruce it up and make it public on GitHub.
I'll make a PR here with an optional UI component and documentation on how to integrate it with gatsy-starter-gcn.

**Comment by johnmeredith** [comment]
Superb!

**Comment by OrKoN** [comment]
I created a plugin for JustComments: https://www.gatsbyjs.org/packages/gatsby-plugin-just-comments/

And JustComments got a new look now with more customization options: https://just-comments.com/demo.html

**Comment by ryanwiemer** [comment]
I have decided not to add any comment functionality to keep the repo simple. Thank you for the discussion though.
