### ISSUE TITLE
Error with Image being a null

### ISSUE THREAD

**Issue by d-ivashchuk** [ryanwiemer/gatsby-starter-gcn#49]
First of all thanks a lot for the starter! You did a fantastic job on it.

I've started to modify it and play with contentful+netlify integration and everything worked fine but lately when I run `gatsby develop` there is no error in terminal and everything seems correct but I get nothing rendered because of some error concerning image being `null`.

I didn't change any logic apart from adding `react headroom`. Moreover if I change something and push changes to github which triggers netlify build everything is working fine on the server and site is live without any errors. So basically I can't develop locally.

I would much appreciate your help with it! Thanks!

Here is stack trace:
```
The above error occurred in the <Card> component:
    in Card (at templates/index.js:29)
    in ul (created by Context.Consumer)
    in StyledComponent (created by CardList__List)
    in CardList (at templates/index.js:28)
    in section (created by Context.Consumer)
    in StyledComponent (created by Container__Wrapper)
    in Container (at templates/index.js:26)
    in div (at Layout.js:23)
    in ThemeProvider (at Layout.js:21)
    in div (at Layout.js:13)
    in Template (at templates/index.js:19)
    in Index (created by PageRenderer)
    in PageRenderer (at json-store.js:93)
    in JSONStore (created by EnsureResources)
    in ScrollContext (at root.js:63)
    in RouteUpdates (at root.js:62)
    in EnsureResources (at root.js:60)
    in RouteHandler (created by Root)
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl (created by Context.Consumer)
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by LocationProvider)
    in LocationProvider (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (created by Root)
    in Root (at root.js:119)
    in _default (created by HotExported_default)
    in AppContainer (created by HotExported_default)
    in HotExported_default (at app.js:56)
```

**Comment by d-ivashchuk** [comment]
I have an idea now that probably tokens got messed up or something like that happened after another deploy so it works for Netlify and fails for local fetch.

**Comment by ryanwiemer** [comment]
@d-ivashchuk, 

Ahh gotcha. Let me know if having the correct tokens ends up being the issue. 

The only other thing I would recommend if you have issues when developing locally is to clear out the site's local cache via [`npm run clean`](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/package.json#L54).

**Comment by d-ivashchuk** [comment]
For now cloning to other machine and running `setup` once more and filling the tokens solved the issue, just wondering where did it come from. Closing it for for now, as the problem does not seem critical, if I will have it once more after deploy or contentful changes I will reopen it.

**Comment by ryanwiemer** [comment]
Sounds good. Thanks!

**Comment by kirso** [comment]
Hmmm seems like I have the same problem. Everything worked fine, but then both production and local builds fail 

![image](https://user-images.githubusercontent.com/2138870/50380955-e5c0ab80-06b4-11e9-80ad-20315003b6ce.png)

**Comment by ryanwiemer** [comment]
@kirso are you sure the image you are using is "published" on Contentful? Did you try clearing the local cache as I suggested before?

**Comment by kirso** [comment]
@ryanwiemer - yes, everything was published, nothing removed and the site just started failing after I believe Gatsby released a new update. I just started from scratch and will rebuild the site again. Thanks, Ryan for answering so quickly! Bes starter ever!

**Comment by ryanwiemer** [comment]
@kirso, strange, well let me know if a fresh install works for you. Might be an old Gatsby bug or something else. Glad the starter is helpful to you.
