### ISSUE TITLE
Blurry Images on Desktop

### ISSUE THREAD

**Issue by johnmeredith** [ryanwiemer/gatsby-starter-gcn#50]
This might well be a mistake on my part configuring Contentful but I get blurry images on desktop browsers. For example:

https://www.archetextur.es/interoperability-is-poorly-defined-and-subsequently-misused/

It seems clear on mobile though?

**Comment by ryanwiemer** [comment]
@johnmeredith, 

On the [post.js](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/src/templates/post.js#L66) template the GraphQL query has max width for media set to 1800px. If you want bigger images simply make that larger and ensure you have high quality images uploaded in Contentful.

**Comment by ryanwiemer** [comment]
I'm gonna close this out for now as I am fairly confident that is the issue. If however you still have issues let me know and I can reopen it.
