### ISSUE TITLE
webpack absolute path error

### ISSUE THREAD

**Issue by dattila23** [ryanwiemer/gatsby-starter-gcn#52]
Hello!

I build locally (gatsby build) but it is error:

 WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a co
  nfiguration object that does not match the API schema.
   - configuration.context: The provided value "e:\\!Project\\GatsBy\\gatsby-starter-gcn" contains exc
  lamation mark (!) which is not allowed because it's reserved for loader syntax.
     -> The base directory (absolute path!) for resolving the `entry` option. If `output.pathinfo` is
  set, the included pathinfo is shortened to this directory.
   - configuration.output.path: The provided value "e:\\\\!Project\\\\GatsBy\\\\gatsby-starter-gcn\\\\
  public" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
     -> The output directory as **absolute path** (required).

What is the fail?
Thanks

**Comment by ryanwiemer** [comment]
@dattila23, from the description of the error it sounds like it may be related to what you named the parent folder: `!Project`. The `!` character as it states is reserved for Webpack and can't be used. 

Can you try renaming that folder or putting it somewhere else to see if that resolves the problem?

**Comment by dattila23** [comment]
Oh yes. It was the problem. Thanks a lot!
