### ISSUE TITLE
allContentfulPage error

### ISSUE THREAD

**Issue by snbasics** [ryanwiemer/gatsby-starter-gcn#54]
I've just downloaded the starter theme and when I attempt to run `gatsby develop` I get the following errors:
```
error Cannot read property 'allContentfulPage' of undefined
  TypeError: Cannot read property 'allContentfulPage' of undefined
```
and
```
error UNHANDLED REJECTION
TypeError: Cannot read property 'allContentfulPage' of undefined
```

I only found allContentfulPage in Gatsby-node.js. on lines 118 and 127 but I didn't spot an issue. Any idea what I am doing wrong? 

Thanks in advance, Isaac

**Comment by ryanwiemer** [comment]
@snbasics,

Did you go through the full [setup process](https://github.com/ryanwiemer/gatsby-starter-gcn#setup-contentful) including Contentful?

**Comment by snbasics** [comment]
@ryanwiemer Thanks so much for your help. I had gone through it but I decided to create a new Contentful space and try again, that solved it. I really like the theme and appreciate the time you've put in and the help.

**Comment by ryanwiemer** [comment]
Cool. Glad you got it resolved.
