### ISSUE TITLE
Async error and GraphQL error

### ISSUE THREAD

**Issue by hrashid** [ryanwiemer/gatsby-starter-gcn#55]
I tried the local install and connected it to my Contentful space. I've confirmed that everything's connected because the content has been created in Contentful (posts, pages, and tags).

When I try to run "gatsby develop" I get the following errors:

----------------------------------------------
error Plugin gatsby-transformer-remark returned an error

Error: /Users/hrashid/Sites/gatsby-starter-gcn/node_modules/gatsby-remark-images-contentful/index.js:25
  module.exports = async ({
                         ^
  SyntaxError: Unexpected token (

-----------------------------------------------

error GraphQL Error Unknown field `html` on type `MarkdownRemark`

  file: /Users/hrashid/Sites/gatsby-starter-gcn/src/templates/index.js

------------------------------------------------

any idea how to fix this?

**Comment by hrashid** [comment]
ahh...i updated node and fixed it...closing

**Comment by ryanwiemer** [comment]
Gotcha. Glad you were able to resolve it on your own. Best of luck to you!

**Comment by hrashid** [comment]
Thanks for all your work on this.  It's an awesome project!
