### ISSUE TITLE
Failed to deploy on Netlify - Build script returned non-zero exit code: 1

### ISSUE THREAD

**Issue by victor-balta** [ryanwiemer/gatsby-starter-gcn#56]
Hi,

The starter works perfectly on local env, but when I try to deploy it on Netlify it gives me this error

3:30:25 PM: **Error running command: Build script returned non-zero exit code: 1**

Any ideas how to fix that?  (I used the latest release)
Thank you

**Comment by ryanwiemer** [comment]
@victor-balta Did you add the [environment variables](https://github.com/ryanwiemer/gatsby-starter-gcn#netlify-deployment-from-git-recommended) in Netlify? Also could provide more of the log from Netlify?

**Comment by victor-balta** [comment]
Hi @ryanwiemer,

The issue was that I provided the wrong token. For some reasons, I thought I had to put the content management token. Maybe it will be useful to specify in the readme which one to use for beginners like me.

I will close the ticket. Thank you anyway for your support.

**Comment by ryanwiemer** [comment]
Thanks for the update and feedback. I will take a look at the README to see if I can improve it.
