### ISSUE TITLE
Canonical Link Check

### ISSUE THREAD

**Issue by johnmeredith** [ryanwiemer/gatsby-starter-gcn#58]
Hi there
I’ve clearly missed something in the config of my site but when running an SEO check for 
https://sitechecker.pro/seo-report/https://www.archetextur.es/ i get the canonical link to your demo page at https://gcn.netlify.com/. Where can I reconfigure this to my domain?

Sorry for the dumb question!
J

**Comment by johnmeredith** [comment]
Additionally I just ran this through the Google URL inspection for a specific page and found 
Indexing allowed? Yes
User-declared canonical: https://gcn.netlify.com/a-pattern-for-cardiovascular-assessment/

I just haven’t configured something right? And would a sitemap help?

**Comment by ryanwiemer** [comment]
@johnmeredith - Did you update your [siteConfig.js](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/src/utils/siteConfig.js)? If not that would explain what you are seeing.

**Comment by johnmeredith** [comment]
Yes I did. All but the siteURL. WTF?!? #idiotme
