### ISSUE TITLE
TypeError: Cannot read property 'allContentfulPost' of undefined

### ISSUE THREAD

**Issue by humet** [ryanwiemer/gatsby-starter-gcn#62]
Hi,

I am getting this error when I'm trying to build Gatsby or even put it into develop mode. 

I have tried to use an existing space that already contains content. Could that be an issue? Does it always have to start with a blank space on Contentful?

Thanks

**Comment by ryanwiemer** [comment]
@humet, 

Yes, for the [setup process](https://github.com/ryanwiemer/gatsby-starter-gcn#setup-contentful) to work properly you need to start with an empty Space. The setup script creates the necessary content model and placeholder content. 

In theory you could using an existing space but unless your content model is exactly the same it will not work. Let me know if that makes sense or if you have any questions.

**Comment by humet** [comment]
Thanks @ryanwiemer. 

Is there any info of where to start with working with an existing space? The content I'm wanting to use is very similar to the placeholder content.

**Comment by ryanwiemer** [comment]
@humet, no I do not have any documentation on that. Here are some screenshots though of the content model you would have to replicate for the 3 content types I use. Your content has to be formatted exactly like this including the name of the fields. It's probably more work to do this than just start over and migrate over the old content. 

**Page**
<img width="1221" alt="page" src="https://user-images.githubusercontent.com/5171579/57736403-a7745a80-765c-11e9-8f8c-5144dd60b657.png">

**Post** 
<img width="1225" alt="post" src="https://user-images.githubusercontent.com/5171579/57736408-ad6a3b80-765c-11e9-8e4e-7cb4a0b15d35.png">

**Tag**
<img width="1219" alt="tag" src="https://user-images.githubusercontent.com/5171579/57736414-b3601c80-765c-11e9-817b-c5d6a5cec3cf.png">
