### ISSUE TITLE
Is there a way to deploy to Github Pages?

### ISSUE THREAD

**Issue by wonhyeongseo** [ryanwiemer/gatsby-starter-gcn#63]
Hello, thank you very much for this starter kit. As a beginner, I want to deploy the blog to Github Pages instead of Netlify. Is this a possibility? How would one edit this repo to deploy to Github Pages?

**Comment by ryanwiemer** [comment]
I don't use GitHub pages but it's definitely possible. From a quick a google search I found the following which may be of interest to you:

https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/

If you still have questions or get stuck I recommend using StackOverflow or something similar. 

Best of luck to you!
