### ISSUE TITLE
Node 12 compatibility

### ISSUE THREAD

**Issue by YasharF** [ryanwiemer/gatsby-starter-gcn#67]
It looks like due to dependency issues the current repo is not compatible with Node 12, however updating the dependencies to the latest seem to fix the compatibility issue.

**Comment by YasharF** [comment]
The versions locked in by package-lock.json are the incompatible ones.  I made a fork of this repo, removed package-lock.json, and tried it, and it didn't choke.

https://github.com/YasharF/gatsby-starter-gcn

`gatsby new unstuck-gatsby git@github.com:YasharF/gatsby-starter-gcn.git`

**Comment by ryanwiemer** [comment]
Thank you @YasharF for creating this issue. I have been meaning to update the dependencies. I will do some testing to make sure there are no issues and then release an update to this starter.

**Comment by ryanwiemer** [comment]
@YasharF This should be resolved as of [`v2.0.6`](https://github.com/ryanwiemer/gatsby-starter-gcn/releases/tag/v2.0.6)

Let me know if you have any issues.
