### ISSUE TITLE
Change post image width

### ISSUE THREAD

**Issue by johnmeredith** [ryanwiemer/gatsby-starter-gcn#69]
Hi there,
Not a bug but a general "I suck" question... I have tweaked the width of each post successfully but cannot see where to change the width of the images included? As a result the post body width is now wider but all images do not match.

Thanks!
John

**Comment by ryanwiemer** [comment]
@johnmeredith 

Do you have an image or link to your repo to better explain what you are referring to? I am just trying to understand if this is a CSS question or if you mean the maxWidth of the image coming back from Contentful.

**Comment by ryanwiemer** [comment]
Assuming you just mean the images inside the post you can edit the maxWidth here: 

https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/gatsby-config.js#L53

**Comment by johnmeredith** [comment]
Nailed it! Thank you.
