### ISSUE TITLE
Images not showing when publishing new blog

### ISSUE THREAD

**Issue by soniCaH** [ryanwiemer/gatsby-starter-gcn#7]
When I publish a new blogpost via contentful, netlify builds the new version successfully, but none of the images appear and a JavaScript error is thrown.

Locally (gatsby develop or gatsby build), all images are loading perfectly fine.

When I delete the blogpost, all images show again as before.

![image](https://user-images.githubusercontent.com/789034/39423550-b4e034d8-4c72-11e8-9e49-fd868c7f6b34.png)

I tried different images and blogposts, but until I delete the entry, nothing works.

**Comment by soniCaH** [comment]
When I check back now, images do load. Maybe it takes some time to mitigate them to all CDN's or something similar?

**Comment by ryanwiemer** [comment]
@soniCaH, Yeah I'm not sure what happened with your particular use case but it sounds like it was a non-issue.

Just an FYI if I ever run into issues the first thing I do is check the build logs and if necessary trigger a manual deploy on Netlify. It's very rarely needed but it seems like a good first step to rule out a CDN or caching issue on either Netlify or Contentful when debugging issues.

Best of luck to you!

**Comment by soniCaH** [comment]
Thanks for the tip. The build logs didnt show any errors or warnings, all went fine.
I did a few manual deploys and the issue persisted. Tried deleting my blogpost: images appeared immediately, created new blogpost: all images were gone. This is still the case now. If I create nee blogposts, images are not showing for a while.

**Comment by ryanwiemer** [comment]
@soniCaH, 

Interesting. So is the current issue that images do not show up at all or that they take too long to load? 

Do you have a live URL that I could look at? It still sounds more like a Netlify / Contentful issue than a problem with the template but I'm happy to to take a quick look if it is helpful. 

The only other generic advice I can give is to make sure that you are using the latest versions of all the dependencies such as Gatsby, etc. 

Thanks,
Ryan

**Comment by soniCaH** [comment]
URL is https://kevin.van-ransbeeck.be/test-blog/

The images don't load at all and a JavaScript error is thrown.
After a while (last time I checked after 2 hours) they suddenly work, so maybe by the time you check the URL, it's already "fixed" :).

<img width="1529" alt="screen shot 2018-04-30 at 20 41 28" src="https://user-images.githubusercontent.com/789034/39444165-1a737ffa-4cb7-11e8-8db8-1569bc3bbb56.png">
<img width="1428" alt="screen shot 2018-04-30 at 20 41 40" src="https://user-images.githubusercontent.com/789034/39444167-1a8ebc0c-4cb7-11e8-8937-65c0c71e16b7.png">


Build log:

```8:40:40 PM: Build ready to start
8:40:42 PM: Fetching cached dependencies
8:40:42 PM: Starting to download cache of 71.3MB
8:40:43 PM: Finished downloading cache in 775.378263ms
8:40:43 PM: Starting to extract cache
8:40:47 PM: Finished extracting cache in 3.684772598s
8:40:47 PM: Finished fetching cache in 4.577662812s
8:40:47 PM: Starting to prepare the repo for build
8:40:47 PM: Preparing Git Reference refs/heads/master
8:40:48 PM: Starting build script
8:40:48 PM: Installing dependencies
8:40:48 PM: Started restoring cached node version
8:40:51 PM: Finished restoring cached node version
8:40:51 PM: v8.11.1 is already installed.
8:40:52 PM: Now using node v8.11.1 (npm v5.6.0)
8:40:52 PM: Attempting ruby version 2.3.6, read from environment
8:40:54 PM: Using ruby version 2.3.6
8:40:54 PM: Using PHP version 5.6
8:40:54 PM: Started restoring cached node modules
8:40:54 PM: Finished restoring cached node modules
8:40:54 PM: Started restoring cached yarn cache
8:40:54 PM: Finished restoring cached yarn cache
8:40:55 PM: Installing NPM modules using Yarn version 1.3.2
8:40:56 PM: yarn install v1.3.2
8:40:56 PM: [1/4] Resolving packages...
8:40:57 PM: success Already up-to-date.
8:40:57 PM: Done in 1.19s.
8:40:57 PM: NPM modules installed using Yarn
8:40:57 PM: Started restoring cached go cache
8:40:57 PM: Finished restoring cached go cache
8:40:57 PM: unset GOOS;
8:40:57 PM: unset GOARCH;
8:40:57 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.10.linux.amd64';
8:40:57 PM: export PATH="/opt/buildhome/.gimme/versions/go1.10.linux.amd64/bin:${PATH}";
8:40:57 PM: go version >&2;
8:40:57 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.10.linux.amd64.env';
8:40:57 PM: go version go1.10 linux/amd64
8:40:57 PM: Installing missing commands
8:40:57 PM: Verify run directory
8:40:57 PM: Executing user command: gatsby build
8:40:59 PM: success delete html and css files from previous builds — 0.056 s
8:40:59 PM: success open and validate gatsby-config — 0.023 s
8:40:59 PM: success copy gatsby files — 0.023 s
8:41:00 PM: success onPreBootstrap — 0.460 s
8:41:00 PM: Starting to fetch data from Contentful
8:41:00 PM: Fetching default locale
8:41:00 PM: default local is : nl-BE
8:41:01 PM: contentTypes fetched 3
8:41:01 PM: Updated entries  12
8:41:01 PM: Deleted entries  0
8:41:01 PM: Updated assets  8
8:41:01 PM: Deleted assets  0
8:41:01 PM: Fetch Contentful data: 751.949ms
8:41:01 PM: success source and transform nodes — 0.824 s
8:41:01 PM: success building schema — 0.252 s
8:41:01 PM: success createLayouts — 0.034 s
8:41:01 PM: success createPages — 0.048 s
8:41:01 PM: success createPagesStatefully — 0.020 s
8:41:01 PM: success onPreExtractQueries — 0.004 s
8:41:01 PM: success update schema — 0.169 s
8:41:01 PM: success extract queries from components — 0.133 s
8:41:02 PM: success run graphql queries — 0.233 s
8:41:02 PM: success write out page data — 0.003 s
8:41:02 PM: success write out redirect data — 0.001 s
8:41:02 PM: success onPostBootstrap — 0.001 s
8:41:02 PM: info bootstrap finished - 4.254 s
8:41:06 PM: success Building CSS — 4.334 s
8:41:18 PM: success Building production JavaScript bundles — 12.135 s
8:41:22 PM: success Building static HTML for pages — 3.485 s
8:41:22 PM: info Done building in 24.215 sec
8:41:22 PM: Caching artifacts
8:41:22 PM: Started saving node modules
8:41:22 PM: Finished saving node modules
8:41:22 PM: Started saving yarn cache
8:41:22 PM: Finished saving yarn cache
8:41:22 PM: Started saving pip cache
8:41:22 PM: Finished saving pip cache
8:41:22 PM: Started saving emacs cask dependencies
8:41:22 PM: Finished saving emacs cask dependencies
8:41:22 PM: Started saving maven dependencies
8:41:22 PM: Finished saving maven dependencies
8:41:22 PM: Started saving boot dependencies
8:41:22 PM: Finished saving boot dependencies
8:41:22 PM: Started saving go dependencies
8:41:22 PM: Finished saving go dependencies
8:41:22 PM: Build script success
8:41:22 PM: Starting to deploy site from 'public/'
8:41:23 PM: Starting post processing
8:41:24 PM: Post processing done
8:41:24 PM: Site is live
8:41:36 PM: Finished processing build request in 54.884189299s```

**Comment by ryanwiemer** [comment]
Thanks for the additional information. The build log looks good to me and I am not able to replicate the issue. Everything seems to be working properly for me here in San Francisco, USA. 

![Gif](https://media.giphy.com/media/2scM5RpKswPWDfPIPt/giphy.gif)

Maybe try opening the URL in a new window? Perhaps something is getting cached in your browser session or something although I am just speculating at this point. Does it behave differently in other browsers?

**Comment by soniCaH** [comment]
Hey @ryanwiemer 

Guess it is something browser/cache related.
Safari: images not loading + JS error - suddenly works after an hour or so
Chrome: images loading + no JS error

![netlify-480 mov](https://user-images.githubusercontent.com/789034/39534283-908c1c4e-4e31-11e8-96ca-5e12c60631fd.gif)

Thanks for thinking along anyway!

**Comment by ryanwiemer** [comment]
@soniCaH Thanks for the update. Sorry I couldn't be more helpful. Please do let me know if you ever figure out a root cause.
