### ISSUE TITLE
Contentful Rate Limit - Image imports are failing

### ISSUE THREAD

**Issue by zanedev** [ryanwiemer/gatsby-starter-gcn#71]
Hi, thanks I love the starter, have used it in the past without problems. Today I ran setup with a fresh project and I got a ton of asset upload failures and it seemed to finish but when running gatsby there are a lot of graphql errors about missing images and the site doesn't run properly.  Maybe it should be able to handle if images fail more gracefully?  I tried running setup again and it doesn't seem to pick off where it left off asking for space id and other info again.

During setup:
```
The following 4 errors and 12 warnings occurred:

20:16:46 - Rate limit error occurred. Waiting for 1529 ms before retrying...
20:16:49 - Rate limit error occurred. Waiting for 1567 ms before retrying...
20:16:62 - Rate limit error occurred. Waiting for 1511 ms before retrying...
20:16:70 - Rate limit error occurred. Waiting for 1623 ms before retrying...
20:16:80 - Rate limit error occurred. Waiting for 1625 ms before retrying...
20:16:82 - Rate limit error occurred. Waiting for 1670 ms before retrying...
20:17:83 - AssetProcessingTimeout: Asset is taking longer then expected to process.
20:17:21 - AssetProcessingTimeout: Asset is taking longer then expected to process.
20:17:80 - AssetProcessingTimeout: Asset is taking longer then expected to process.
20:17:13 - AssetProcessingTimeout: Asset is taking longer then expected to process.
20:17:54 - Rate limit error occurred. Waiting for 1697 ms before retrying...
20:17:55 - Rate limit error occurred. Waiting for 1675 ms before retrying...
20:17:72 - Rate limit error occurred. Waiting for 1635 ms before retrying...
20:17:73 - Rate limit error occurred. Waiting for 1587 ms before retrying...
20:17:76 - Rate limit error occurred. Waiting for 1691 ms before retrying...
20:17:80 - Rate limit error occurred. Waiting for 1696 ms before retrying...

```

When running gatsby after setup
```
error
The GraphQL query from /Users/zanedev/Projects/gatsby-starter-gcn/src/templates/index.js failed.

Errors:
  Cannot read property 'image' of undefined

  GraphQL request (14:11)
  13:           title
  14:           fluid(maxWidth: 1800) {
                ^
  15:             ...GatsbyContentfulFluid_withWebp_noBase64
  ,Cannot read property 'image' of undefined

  GraphQL request (14:11)
  13:           title
  14:           fluid(maxWidth: 1800) {
                ^
  15:             ...GatsbyContentfulFluid_withWebp_noBase64

URL path:
  /
Context:
  {
    "limit": 7,
    "skip": 0,
    "numPages": 3,
    "currentPage": 1
  }
Plugin:
  none
Query:
  query usersZaneProjectsGatsbyStarterGcnSrcTemplatesIndexJs3965247395(
    $skip: Int!
    $limit: Int!
  ) {
    allContentfulPost(sort: {fields: [publishDate], order: DESC}, limit: $limit, skip: $skip) {
      edges {
        node {
          title
          id
          slug
          publishDate(formatString: "MMMM DD, YYYY")
          heroImage {
            title
            fluid(maxWidth: 1800) {
              ...GatsbyContentfulFluid_withWebp_noBase64
            }
          }
          body {
            childMarkdownRemark {
              timeToRead
              html
              excerpt(pruneLength: 80)
            }
          }
        }
      }
    }
  }

  fragment GatsbyContentfulFluid_withWebp_noBase64 on ContentfulFluid {
    aspectRatio
    src
    srcSet
    srcWebp
    srcSetWebp
    sizes
  }
```

**Comment by zanedev** [comment]
Tried running setup again and ran into the same problems.  Maybe it should be smaller less assets for this starter?

**Comment by ryanwiemer** [comment]
@zanedev, 

Looking at the log it seems like a rate limit from Contentful which is causing the issues. Not sure if there is much I can do about that but I'll reach out to Contentful for more specifics on the rate limit on my account hosting the starter content.

**Comment by zanedev** [comment]
Yeah ran into the same thing with another starter but I don’t even have any other spaces on this test account so not sure why it would specifically rate limit my account only.  I’ll try a new account tonight and see if the same thing happens.

**Comment by ryanwiemer** [comment]
@zanedev to clarify the rate limit causing the issue may actually be on my account not yours. In the setup process it grabs the placeholder images and content directly from my Contentful account that I setup specifically for that purpose. 

My best guess it that other people were setting up their site via this starter at the same time which may have triggered the rate limit on my account. 

In any case give it another shot and let me know if you keep having the same issue.

**Comment by zanedev** [comment]
Okay it looks like it worked after running it today but there was still rate limit errors in the output.  I think the issue was not the rate limit but the other errors `AssetProcessingTimeout: Asset is taking longer then expected to process.` since the problem was missing assets but it's not clear which was actually resulting in a missing asset from the error output.

Anyway I wonder if this is happening to anyone else?  I'm doing a talk at the next JAMstack SF meetup in a few weeks and was thinking of using the starter during a live demo so was hoping it will be smooth but it's not a big deal I can keep my existing one working and fall back to that if needed.

**Comment by ryanwiemer** [comment]
@zanedev 

Personally I have not run into the issue before. In any case if you continue to have problems or if anyone else experiences issues with the rate limit or asset processing timing out on Contentful let me know. 

P.S. 
Feel free to shoot me a DM on Twitter with the details for when you are speaking. I work in SF so if I'm available maybe I can attend. 

https://twitter.com/ryanwiemer

**Comment by zanedev** [comment]
@ryanwiemer will do thanks!

**Comment by Roman-ZN** [comment]
The issue is still actual.
