### ISSUE TITLE
Set static home page and blog urls

### ISSUE THREAD

**Issue by ghost** [ryanwiemer/gatsby-starter-gcn#72]
Hi, 
I am trying to set one page as static home page and the blogs inside a blog page with the following url structure
```
example.com/blog/page/1 
example.com/blog/page/2
example.com/blog/page/3
```

I changed the url here: 
https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/gatsby-node.js#L45

but it broke the pagination

**Comment by ryanwiemer** [comment]
@LittleHamster, 

Thanks for logging the issue. I will have to look into adding a configureable basePath in order to support that.

**Comment by DuncanLHS** [comment]
@ryanwiemer it would be great if you could build that in to the setup.
@LittleHamster I have managed to do this and you have to change the paths in several places on top of the one you have highlighted as well as creating a new index.js. Basically anywhere there is a link to a blog post,
I've migrated the tags to /blog/tags as well.
I've not been totally successful as I'm getting a console warning about using the Link component for an external link, I've got double forward slashes (//blog) somewhere but I haven't found them yet, all the links still lead to /blog so not sure what's going on and I'm not the best person to describe in any detail how to do what you're asking.

Edit: fixed the console error. Sure there's an easier way than editing links everywhere, perhaps I'll try a parameter in SiteConfig.js

**Comment by ghost** [comment]
@LittleHobbyShop 
What I noticed is that even after I changed the url, the website is still accessible through old links, have you had that issue?

**Comment by DuncanLHS** [comment]
> @LittleHobbyShop
> What I noticed is that even after I changed the url, the website is still accessible through old links, have you had that issue?

Try running: `npm run clean`

**Comment by ghost** [comment]
@LittleHobbyShop 
Any chance you can share your fix? or make a pull request so @ryanwiemer can merge it? I have not had any success setting a home page and another page called blog where I could list all blog items

**Comment by DuncanLHS** [comment]
@LittleHamster, I won't make a pull request as I'm very new to this and I feel like it can probably done better so i'll try and explain what I did. I've done a lot on top of this so might not be perfect and I haven't tested the RSS feed yet.

Copy /src/templates/index.js into /src/pages/index.js
Remove children of `<Container/>` in /src/pages/index.js. This is now your empty home page.
Rename /src/templates/index.js to blog.js

# In /gatsby-node.js (7 changes):
- Change /blog path and new blog.js template in createPage (2 changes):
```
// Create main home page
      createPage({
        path: `/blog/`,
        component: path.resolve(`./src/templates/blog.js`),
```
- Change /blog path and new template in pagination (2 changes):
```
Array.from({ length: numPages }).forEach((_, i) => {
        createPage({
          path: `/blog/${i + 2}/`,
          component: path.resolve(`./src/templates/blog.js`),
```
- Change /blog path to individual post slug (1 change):
```
posts.forEach((edge, i) => {
        const prev = i === 0 ? null : posts[i - 1].node
        const next = i === posts.length - 1 ? null : posts[i + 1].node
        createPage({
          path: `/blog/${edge.node.slug}/`,
```
- Optionally change /blog path for tag slugs (2 changes):
```
tags.map(({ node }) => {
        const totalPosts = node.post !== null ? node.post.length : 0
        const numPages = Math.ceil(totalPosts / postsPerPage)
        Array.from({ length: numPages }).forEach((_, i) => {
          createPage({
            path:
              i === 0 ? `/blog/tag/${node.slug}/` : `/blog/tag/${node.slug}/${i + 1}/`,
```
# In gatsby-config.js (for RSS feed settings)(3 changes):
- Change rssMetaData feed_url (1 change)
```
siteMetadata: {
    siteUrl: config.siteUrl,
    rssMetadata: {
      site_url: config.siteUrl,
      feed_url: `${config.siteUrl}/blog/rss.xml`,
```
- Change gatsby-plugin-feed url and guid settings (2 changes)
```
feeds: [
          {
            serialize(ctx) {
              const rssMetadata = ctx.query.site.siteMetadata.rssMetadata
              return ctx.query.allContentfulPost.edges.map(edge => ({
                date: edge.node.publishDate,
                title: edge.node.title,
                description: edge.node.body.childMarkdownRemark.excerpt,

                url: rssMetadata.site_url + '/blog/' + edge.node.slug,
                guid: rssMetadata.site_url + '/blog/' + edge.node.slug
```
# src/components/Card.js
Change Link to:
`<Link to={`/blog/${slug}/`}>`

# src/components/Card.js
Change pathPrefix:
`const pathPrefix = typeof slug === 'string' ? `/blog/tag/${slug}` : '/blog'`

# src/components/PostLink.js
Change PreviousLink and NextLink to
```
<PreviousLink to={`/blog/${props.previous.slug}/`}>
            &#8592; Prev Post
          </PreviousLink>
        )}
        {props.next && (
          <NextLink to={`/blog/${props.next.slug}/`}>Next Post &#8594;</NextLink>
```
# src/Components/TagList.js
Change Link to only if you changed the tag path in gatsby-node.js
`<Link to={`/blog/tag/${tag.slug}/`}>{tag.title}</Link>`

# src/Components/Menu.js
Add additional `<li>` for link in the nav bar
 ```
<li>
     <Link to="/blog/" activeStyle={activeLinkStyle}>
           Blog
    </Link>
</li>
```

Hopefully that's everything.

**Comment by ryanwiemer** [comment]
Hey guys,

I'm closing this ticket for now. I will reevaluate this as a potential feature when I convert the starter to be a Gatsby Theme.

**Comment by ghost** [comment]
@ryanwiemer 
any updates on this?

**Comment by ghost** [comment]
@ryanwiemer 
any updates if you would be implementing this any time soon?
thanks

**Comment by ghost** [comment]
@ryanwiemer 
will you be looking into this since you are updating this project :P

**Comment by ryanwiemer** [comment]
@LittleHamster potentially. haha. 

I am a little conflicted on it. Personally I feel options are better suited for a theme rather than a starter. I added similar functionality to [gatsby-theme-amsterdam](https://github.com/ryanwiemer/gatsby-theme-amsterdam) along with other optional features like page transitions, progress indicators, color mode toggle, etc.

I purposely left this starter more bare bones.

**Comment by ghost** [comment]
@ryanwiemer I agree, it is best to leave it without any customization but I just thought having a static homepage option would help a lot of people who try to use this starter as a portfolio builder.

**Comment by ryanwiemer** [comment]
Yeah, that's fair. I'll reopen this ticket and rethink the best path forward. No promises yet. 😉

**Comment by ryanwiemer** [comment]
A configurable `basePath` has been added in [v2.1.3](https://github.com/ryanwiemer/gatsby-starter-gcn/releases/tag/v2.1.3). 

**NOTE:** This will affect  the templates for `post`, `posts` and `tag`. `page` will not be affected. 

**`basePath: 'blog'`**
- www.example.com/blog/
- www.example.com/blog/post-name/
- www.example.com/blog/tag/tag-name/
- www.example.com/contact/  ← This is a "page" so the `basePath` is not automatically added. 

If you have any questions just let me know.

**Comment by ghost** [comment]
wooho awesome ❤️

**Comment by ryanwiemer** [comment]
@LittleHamster Feel free to test it out and let me know if you run into any issues or questions.

**Comment by ghost** [comment]
@ryanwiemer 
tested it and it works great, thanks a lot

**Comment by ryanwiemer** [comment]
No problem
