### ISSUE TITLE
Image path

### ISSUE THREAD

**Issue by ghost** [ryanwiemer/gatsby-starter-gcn#73]
I noticed on the demo: https://gcn.netlify.com/
images are loaded from here:
https://images.ctfassets.net/

is it possible to load images through the domain (https://gcn.netlify.com/) ?

**Comment by ryanwiemer** [comment]
@LittleHamster, 

This starter was specifically created to be used with Contentful. https://images.ctfassets.net/ is the asset domain that Contentful uses for images coming from the CMS. 

https://www.contentful.com/blog/2017/12/08/change-of-the-contentful-asset-domain/

**Comment by ghost** [comment]
Thanks for your reply, I think in their own starter the path is set differently and is not loaded this way, have you seen that one? Thanks
