### ISSUE TITLE
Customizing single post slug

### ISSUE THREAD

**Issue by ghost** [ryanwiemer/gatsby-starter-gcn#74]
Is it possible to change the single post slug?

by default it is:
```
example.com/contentful-slug/
```

Can it be these variations?
```
example.com/[year]/[month]/contentful-slug/
example.com/[year]/[month]/[day]/contentful-slug/
```

where the year, month and day are from the publication date

**Comment by ryanwiemer** [comment]
@LittleHamster, no at the moment that is not an option. In the future perhaps when I convert this starter into a theme I will look into adding that functionality.

**Comment by ghost** [comment]
@ryanwiemer 
do you know how should I get that url structure in the mean time?

**Comment by ryanwiemer** [comment]
Closing this ticket for now. I will reevaluate this as a potential feature when I convert the starter to be a Gatsby Theme.
