### ISSUE TITLE
Static site?

### ISSUE THREAD

**Issue by Kevin-Prichard** [ryanwiemer/gatsby-starter-gcn#76]
Hi, thank you for writing this starter, which I tried -- but was surprised to find an external service dependency when I ran `gatsby build`:

`  Error: Contentful space ID and access token need to be provided.`

Question: how can a site be both "static" (as the repo description says) but also dependent upon an external API?  Is that static anymore? Asking here because I don't see a clear answer on gatsbyjs.org/.com, and the depth of this starter indicates you have insight about Gatsby.

I tried out several starter sites from Gatsby, and found they had external API dependencies, like Contentful or Netlify.

See, I thought that "static site generator" meant you define pages and content, then build and go: static pages get generated to disk, which then you sync to your server, where all your dependencies live as static URL resources, and now you're done.

Has the term "static site generator" been subsumed by headless CMS, which is how this starter feels?

Thanks, and sorry in advance it this is annoying, but I'm looking for a truly static site generator, one with no live/dynamic service dependencies.

**Comment by ryanwiemer** [comment]
@Kevin-Prichard 

Great question although this seems better suited for a discussion about the philosophy of Gatsby and  "static site generators" in general rather than a GitHub issue on a specific starter. 

I'm gonna recommend you post your questions to: 

https://spectrum.chat/gatsby-js

Best of luck to you!
