### ISSUE TITLE
How do I remove these icons?

### ISSUE THREAD

**Issue by ghost** [ryanwiemer/gatsby-starter-gcn#78]
Is it possible to remove these icons?
![image](https://user-images.githubusercontent.com/10330481/62092650-ed948f80-b243-11e9-989d-dbe5726bf859.png)

https://gcn.netlify.com/about/#woofer

the ones linking to headlines
thanks

**Comment by ryanwiemer** [comment]
@LittleHamster that is part of the [gatsby-remark-autolink-headers plugin](https://www.gatsbyjs.org/packages/gatsby-remark-autolink-headers/?=markdown%20auto%20link#options)

You can set icon to `false` in the options for that particular plugin. 

https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/gatsby-config.js#L49

**Comment by ghost** [comment]
@ryanwiemer 
thank you :) I set it to false but it didnt remove the icon so I just removed that plugin
thank you again for the quick response
