### ISSUE TITLE
Filter posts just for certain tags

### ISSUE THREAD

**Issue by ghost** [ryanwiemer/gatsby-starter-gcn#79]
Is it possible to filter posts shown by tags? so I want all the posts with TagA be visible on homepage and previous pages. But still be able to view specific posts tags here (which are hidden from homepage)
```
../tag/TagB/
../tag/TagC/
```

**Comment by ryanwiemer** [comment]
So if I understand this correctly you want to exclude specific posts from the homepage? Is that right? 

That can certainly be done via the GraphQL query on the [index.js](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/src/templates/index.js#L47-L77) template. I would recommend reading the Gatsby Docs on the topic of [GraphQL - filter](https://www.gatsbyjs.org/docs/graphql-reference/#filter).
