### ISSUE TITLE
Page transition animation

### ISSUE THREAD

**Issue by ghost** [ryanwiemer/gatsby-starter-gcn#83]
I saw this example from your repos 
https://github.com/ryanwiemer/gatsby-using-page-transitions
I think it would be nice if you can add it to this project too :)

**Comment by ryanwiemer** [comment]
Thanks for the suggestion. I will keep that in mind.

**Comment by ryanwiemer** [comment]
I decided not to add this feature as I want to keep this repo simple. Thanks for the suggestion though.

**Comment by ghost** [comment]
ok 

![image](https://user-images.githubusercontent.com/10330481/73604282-0b78df00-455c-11ea-891b-342d4a1befba.png)
