### ISSUE TITLE
What Solved JS Caching Issues With Safari #5231?

### ISSUE THREAD

**Issue by trueblood12** [ryanwiemer/gatsby-starter-gcn#84]
Hello! Writing to see what actually solved [Issue 5231]( #https://github.com/gatsbyjs/gatsby/issues/5231). I don't see a solution to issue 5231, but the issue is closed. Any help would be greatly appreciated!

We are experiencing the same issue now with Safari at this time. Open up Safari (non-private window), go to the site, the site is broken (JS error in the console, Gatsby Image images aren't loading, etc...). Open up another tab (keeping the other tab open), go to the site in the new tab, site functions just fine.

_I would like to note that when I'm in a private window, it doesn't matter how many tabs I have open, the site is broken._

Love the starter by the way, thank you!

```
Gatsby v 2.18.6
Mac OS: 10.14.6 (Mojave)
Safari: 13.0.4
```

**Comment by ryanwiemer** [comment]
@trueblood12  If you are referring to [issue 5231](https://github.com/gatsbyjs/gatsby/issues/5231) on the Gatsby repo I believe it was resolved once `v2` was officially released. 

Are you on the latest version of Gatsby and still experiencing any issues? If so please file an issue on the Gatsby repo. 

Thanks!

**Comment by trueblood12** [comment]
Thank you for your reply.

I wanted to share that we found the root cause of this issue. It turns out (after chatting with Netlify support) Netlify has an open defect (since June 2019 or earlier) related to - if you password protect your site with their simple password protection, the password protection screen will cache old JS in Safari.

Here's a [Netlify community link](https://community.netlify.com/t/password-makes-my-js-not-load-cached/1295) where someone was having the same issue back in June, where Netlify support and I provide more detail:

At first, Netlify support blames it on the custom headers set in gatsby-config.js, however, those are not to blame. We had the issue well before that. We also just recently removed them and are still having the issue. The only fix is to remove Netlify simple password protect (until the main issue is fixed).
