### ISSUE TITLE
emotion instead of styled-components, but why?

### ISSUE THREAD

**Issue by ghost** [ryanwiemer/gatsby-starter-gcn#88]
in the recent release you changed styled-components to emotions, was wondering if you could explain why? thanks

**Comment by ryanwiemer** [comment]
I added support for `Theme UI` which requires `Emotion` instead of `styled-components`. You can still use the styled-component syntax though. 

So pretty much all you have to do is replace styled components with the following: 

```
import styled from '@emotion/styled'
```

**Comment by ghost** [comment]
oh ok, I was just wondering because styled-components seems to be more popular based on github stats

https://github.com/styled-components/styled-components
https://github.com/emotion-js/emotion

**Comment by ryanwiemer** [comment]
Yeah. I still like both. If `Theme UI` adds support to switch back to styled-components I may do that in the future. 

The benefits of Theme UI are worth the switch to me and Gatsby seems to be supporting it heavily since the creator works at Gatsby. 

https://theme-ui.com/
