### ISSUE TITLE
what is query.js file for?

### ISSUE THREAD

**Issue by ghost** [ryanwiemer/gatsby-starter-gcn#89]
noticed this directory `src/gatsby/data/query.js` we have pages in the template directory, what is this file and where is it used?

**Comment by ryanwiemer** [comment]
The `/gatsby/` folder is basically just the `gatsby-node.js` file broken out into separate files to make it easier to manage. `query.js` contains the GraphQL queries necessary to build the pages in `gatsby-node.js`.

**Comment by ghost** [comment]
i see, thanks for the info
