### ISSUE TITLE
page nav dropdown bug

### ISSUE THREAD

**Issue by ghost** [ryanwiemer/gatsby-starter-gcn#90]
<img width="246" alt="image" src="https://user-images.githubusercontent.com/10330481/73604517-1e8dae00-4560-11ea-9cc9-348578cd5e56.png">

the drop down shows up like this

**Comment by ryanwiemer** [comment]
Thanks for pointing this out. ~~Probably related to z-index. Any info on browser, or OS?~~

I was able to replicate it on FireFox. Should be a simple fix.

**Comment by ryanwiemer** [comment]
fixed in [v2.1.2](https://github.com/ryanwiemer/gatsby-starter-gcn/releases/tag/v2.1.2)
