### ISSUE TITLE
Download images locally without using contentful cdn

### ISSUE THREAD

**Issue by ghost** [ryanwiemer/gatsby-starter-gcn#92]
I think `gatsby-source-contentful` recently added this option: 
https://www.gatsbyjs.org/packages/gatsby-source-contentful/#download-assets-for-static-distribution

I tried to add this to the project a few weeks ago but not successful , all images still loaded from the contentful cdn

**Comment by ryanwiemer** [comment]
From my understanding that would require changing the queries for the images and using `gatsby-source-filesystem`. 

That is not something I will be doing for this particular project.
