### ISSUE TITLE
RSS Support

### ISSUE THREAD

**Issue by Swalloow** [ryanwiemer/gatsby-starter-gcn#96]
The RSS feed seems to remove through issue #85 
Why was it deleted?

**Comment by ryanwiemer** [comment]
@Swalloow I wanted to keep this starter simple and "bare bones" so I decided to remove it. 

Of course if you want to add it back for your own site there is an [official Gatsby article](https://www.gatsbyjs.org/docs/adding-an-rss-feed/) with RSS instructions.
