### ISSUE TITLE
Changing body font styling for the entire site 

### ISSUE THREAD

**Issue by ghost** [ryanwiemer/gatsby-starter-gcn#98]
sorry this might be off-topic question but I can't seem to figure out how to change the body styling. 

I want to add something like this so the font is applied globally: 
```
body{
  font-size: 15px;
  line-height: 1.1;
  font-weight: 400;
}
```

I added the font name here: 
https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/src/gatsby-plugin-theme-ui/index.js#L11

but now where can I apply font size, line height and font weight?
editing https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/src/styles/globalStyles.js does nothing

**Comment by ryanwiemer** [comment]
@LittleHamster, 

Font family is controlled at the global level in [gatsby-plugin-them-ui/index.js](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/src/gatsby-plugin-theme-ui/index.js#L11) file as you mentioned. 

As for font-size, line-height and font-weight that is controlled at the individual component level. For example in the [Card](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/src/components/Card.js#L46-L47) component. If you want a quick and dirty way of tweaking the font-size overall you could adjust the css styling on the [body element](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/src/styles/globalStyles.js#L168-L175).

**Comment by ryanwiemer** [comment]
Further clarification: Since I use `em` values you could adjust those by changing the base font size. If the styling references `rem` values then those won't be affected in the same way. 

Useful reference: https://j.eremy.net/confused-about-rem-and-em/

```
body{
  font-size: 93.75%;  
}
```
