### ISSUE TITLE
Demo contents in contentful are still displaying on the website

### ISSUE THREAD

**Issue by Teegreat** [ryanwiemer/gatsby-starter-gcn#99]
I have deleted all the demo contents that were imported into my contentful space but the posts are still showing on my website. Please help me solve this issue.

**Comment by ryanwiemer** [comment]
@Teegreat if you are developing locally you need to restart the server to see changes. If you are referring to the live site you need to "rebuild" it. 

https://github.com/ryanwiemer/gatsby-starter-gcn#useful-tips
